#!/usr/bin/env bash
# Installs Nginx on server and creates a custom html file

# Create a custom HTML file with content "Hello Wold!"
echo "
<html>
  <head>
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
" | sudo tee /www/index.html

# Update the package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx

sudo service nginx start
