#!/usr/bin/env bash
#display "Best Schoo" 8 times and "Hi" on the 9th

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
