#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#Requirements:
#You must use the while loop (for and until are forbidden)
#Note that in this example, we only display the first 70 lines using the head command

hour=0

while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done

echo "Hour: 12"
min=1
while [ $min -lt 60 ]
do
	echo "$min"
	((min++))
done
