#!/usr/bin/env bash

#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
#Requirements:
#You must use the for loop (while and until are forbidden)
#Do not display hidden files

for file in *
do
    # Check if the file is not hidden and contains a dash
    if [[ "$file" != .* && "$file" =~ .*-.* ]]; then
        # Extract the part after the first dash and print it
        echo "${file#*-}"
    fi
done
