#!/usr/bin/env bash
# A script to install 'ufw' firewall
# This script also configures it to block all incoming traffics and allow outgoing traffics
# This scripts also set the firewall to listen to ports '20/tcp' for ssh, '80/tcp' for http and '443/tcp' for https

# Install ufw
sudo apt update
sudo apt install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22), HTTP (port 80), and HTTPS (port 443)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw

echo y | sudo ufw enable

# Display ufw status
sudo ufw status verbose
